# Host to use for canonical URL generation (without trailing slash)
host: https://www.payments.service.gov.uk/

# Header-related options
show_govuk_logo: true
service_name: Pay
service_link: https://www.payments.service.gov.uk/
phase: Beta

# Links to show on right-hand-side of header
header_links:
  About: https://www.payments.service.gov.uk/#main
  Get started: https://www.payments.service.gov.uk/getstarted/
  Documentation: /
  Support: https://www.payments.service.gov.uk/support/
  Sign In: https://selfservice.payments.service.gov.uk/login
footer_links:
  Accessibility: https://www.payments.service.gov.uk/accessibility-statement/

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id: UA-72121642-9

# Show a block at the bottom of the page that links to the page source, so readers can easily contribute back to the documentation.
show_contribution_banner: true
github_repo: alphagov/pay-tech-docs/

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 3

# Prevent robots from indexing (e.g. whilst in development)

google_site_verification: "IJ5HOXpZrISM6la-YO_iX0rBUC5YFftpexygcKLsNs4"

redirects:
  /switching_to_live/before_you_switch_to_live/index.html: /switching_to_live/index.html

multipage_nav: true
collapsible_nav: true

enable_search: true
